name: cime go

on: [push, pull_request]

jobs:
    cime-go:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: build docker
              run: docker build -t gorun . 
            - name: run go
              run: docker run gorun